const SEARCH_INDEX = {
"de": [
{
"id": "home",
"page": "index.html",
"title": "Startseite",
"description": "Deine zentrale Anlaufstelle für Wiki, Tools und Community rund um Metin2",
"keywords": [
"home",
"start",
"hauptseite",
"main"
],
"category": "main",
"icon": "https://m2-helper.com/resources/söldner_2.png",
"searchText": "startseite deine zentrale anlaufstelle für wiki, tools und community rund um metin2 home start hauptseite main"
},
{
"id": "guides",
"page": "guides.html",
"title": "Guides",
"description": "Ausführliche Anleitungen und Strategien für alle Bereiche",
"keywords": [
"guide",
"anleitung",
"hilfe",
"tutorial",
"erklärung"
],
"category": "guides",
"icon": "https://m2-helper.com/resources/guides/quest.png",
"searchText": "guides ausführliche anleitungen und strategien für alle bereiche guide anleitung hilfe tutorial erklärung"
},
{
"id": "server-guide",
"page": "server.html",
"title": "Server Guide",
"description": "Finde den richtigen Server für dich",
"keywords": [
"server",
"anfänger",
"wahl",
"entscheidung",
"vergleich",
"start",
"settings",
"sapphire",
"ruby",
"onyx",
"emerald",
"tigerghost",
"transfers",
"fusion",
"einstieg"
],
"category": "guides",
"icon": "https://m2-helper.com/resources/guides/server.png",
"searchText": "server guide finde den richtigen server für dich server anfänger wahl entscheidung vergleich start settings sapphire ruby onyx emerald tigerghost transfers fusion einstieg"
},
{
"id": "dragon-alchemy",
"page": "dragon-alchemy.html",
"title": "Drachensteinalchemie",
"description": "Kompletter Guide zur Drachensteinalchemie und Steinverbesserung",
"keywords": [
"drachenstein",
"alchemie",
"alchemy",
"dsa",
"upgrade",
"stein",
"system",
"klasse",
"reinheit",
"stufe",
"drachenbohne",
"cor draconis",
"flamme des drachen",
"roh",
"schliff",
"rar",
"antik",
"legendär",
"mythisch",
"matt",
"klar",
"lupenrein",
"brilliant",
"exzellent",
"alchemist",
"zange der zeit",
"drachenzange+",
"elixier der zeit",
"rechner",
"element",
"diamant",
"amethyst",
"onyx",
"granat",
"saphir",
"jade",
"rubin"
],
"category": "systems",
"icon": "https://m2-helper.com/resources/guides/alchemy.png",
"searchText": "drachensteinalchemie kompletter guide zur drachensteinalchemie und steinverbesserung drachenstein alchemie alchemy dsa upgrade stein system klasse reinheit stufe drachenbohne cor draconis flamme des drachen roh schliff rar antik legendär mythisch matt klar lupenrein brilliant exzellent alchemist zange der zeit drachenzange+ elixier der zeit rechner element diamant amethyst onyx granat saphir jade rubin"
},
{
"id": "echoes-of-power",
"page": "echoes-of-power.html",
"title": "Echos der Macht",
"description": "Guide zum Echos der Macht System und Belohnungen",
"keywords": [
"echos",
"macht",
"echo",
"belohnung",
"system",
"echo der macht",
"echo des könnens",
"schaden",
"sapphire",
"onyx"
],
"category": "systems",
"icon": "https://m2-helper.com/resources/guides/Echos_der_Macht.png",
"searchText": "echos der macht guide zum echos der macht system und belohnungen echos macht echo belohnung system echo der macht echo des könnens schaden sapphire onyx"
},
{
"id": "metin-plus",
"page": "metin-plus.html",
"title": "Metin+",
"description": "Guide zum Metin+ System und dessen exklusiven Features",
"keywords": [
"metin+",
"metin plus",
"premium",
"feature",
"system",
"mission",
"herausforderungen",
"belohnungen",
"verlosung",
"buffs"
],
"category": "systems",
"icon": "https://m2-helper.com/resources/guides/m2+.png",
"searchText": "metin+ guide zum metin+ system und dessen exklusiven features metin+ metin plus premium feature system mission herausforderungen belohnungen verlosung buffs"
},
{
"id": "donation-guild",
"page": "donation-guild.html",
"title": "Spendengilde",
"description": "Übersichtliches Tool zum Tracking einer Spendengilde",
"keywords": [
"spendengilde",
"gilde",
"donation",
"tracker",
"verwaltung",
"tool",
"spende",
"elementarverzauberung",
"rechner",
"tapferkeitsmedaillen"
],
"category": "miscellaneous",
"icon": "https://m2-helper.com/resources/guides/server2.png",
"searchText": "spendengilde übersichtliches tool zum tracking einer spendengilde spendengilde gilde donation tracker verwaltung tool spende elementarverzauberung rechner tapferkeitsmedaillen"
},
{
"id": "miscellaneous",
"page": "miscellaneous.html",
"title": "Sonstiges",
"description": "Weitere hilfreiche Guides und Tipps für Metin2",
"keywords": [
"sonstiges",
"tipps",
"tricks",
"auragewand",
"aura",
"gewand",
"gaya",
"schmuckstein",
"rangpunkt",
"rang",
"faq",
"häufig",
"fragen",
"uppchance",
"drachenstein",
"bonus",
"drop",
"seelenstein",
"uppchance",
"feuerrune",
"geiststeinbündel",
"rechner",
"zen-bohne",
"negativ"
],
"category": "miscellaneous",
"icon": "https://m2-helper.com/resources/guides/scroll_open.png",
"searchText": "sonstiges weitere hilfreiche guides und tipps für metin2 sonstiges tipps tricks auragewand aura gewand gaya schmuckstein rangpunkt rang faq häufig fragen uppchance drachenstein bonus drop seelenstein uppchance feuerrune geiststeinbündel rechner zen-bohne negativ"
},
{
"id": "loot-filter",
"page": "loot-filter.html",
"title": "Loot-Filter Einstellungen",
"description": "Finde die richtige Kategorie für ein gesuchtes Item",
"keywords": [
"loot filter",
"lootfilter",
"loot",
"filter",
"items",
"einstellungen",
"settings",
"drop"
],
"category": "tools",
"icon": "https://m2-helper.com/resources/guides/other/Loot-Pass.png",
"searchText": "loot-filter einstellungen finde die richtige kategorie für ein gesuchtes item loot filter lootfilter loot filter items einstellungen settings drop"
},
{
"id": "timer",
"page": "timer.html",
"title": "Timer",
"description": "Erstelle individuelle Timer und nutze sie mit deinen Mitspielern",
"keywords": [
"timer",
"boss",
"raid",
"gruppe",
"channel",
"kanal",
"spawn",
"respawn",
"koordination",
"team",
"echtzeit",
"synchronisation",
"mitspieler",
"individuell"
],
"category": "tools",
"icon": "https://m2-helper.com/resources/accelerator.png",
"searchText": "timer erstelle individuelle timer und nutze sie mit deinen mitspielern timer boss raid gruppe channel kanal spawn respawn koordination team echtzeit synchronisation mitspieler individuell"
},
{
"id": "aura-calculator",
"page": "miscellaneous.html#aura-calculator",
"title": "Auragewand-Rechner",
"description": "Berechne Kosten und Ressourcen für dein Auragewand-Leveling",
"keywords": [
"auragewand",
"aura",
"gewand",
"rechner",
"calculator",
"feuerrune",
"fire rune",
"level",
"cost",
"kosten",
"ressourcen",
"strahlendes auragewand",
"gewöhnliches auragewand",
"eisrune",
"aura der macht"
],
"category": "tools",
"icon": "https://m2-helper.com/resources/guides/other/Strahlendes_Auragewand.png",
"searchText": "auragewand-rechner berechne kosten und ressourcen für dein auragewand-leveling auragewand aura gewand rechner calculator feuerrune fire rune level cost kosten ressourcen strahlendes auragewand gewöhnliches auragewand eisrune aura der macht"
},
{
"id": "gaya-calculator",
"page": "miscellaneous.html#gaya-calculator",
"title": "Gaya-Rechner",
"description": "Berechne wie viel Gaya du aus Schmucksteinen erhältst",
"keywords": [
"gaya",
"rechner",
"calculator",
"schmuckstein",
"gem",
"glimmerstone",
"geiststeinbündel",
"spirit stone bundle",
"meleys hort",
"meley",
"materialien",
"resources"
],
"category": "tools",
"icon": "https://m2-helper.com/resources/guides/other/Gaya.png",
"searchText": "gaya-rechner berechne wie viel gaya du aus schmucksteinen erhältst gaya rechner calculator schmuckstein gem glimmerstone geiststeinbündel spirit stone bundle meleys hort meley materialien resources"
},
{
"id": "rank-points",
"page": "miscellaneous.html#rank-points",
"title": "Rangpunkte Guide",
"description": "Alles über das Rangpunkte-System und wie man sie erhält",
"keywords": [
"rangpunkte",
"rang",
"rank",
"points",
"negativ",
"negative",
"zen-bohne",
"zen bean",
"symbol des weisen kaisers",
"sage kings symbol",
"schadensbonus",
"damage bonus",
"weiser kaiser",
"rang verlieren",
"rank loss",
"tot",
"death",
"rechner",
"calculator"
],
"category": "guides",
"icon": "https://m2-helper.com/resources/guides/other/Zen-Bohne.png",
"searchText": "rangpunkte guide alles über das rangpunkte-system und wie man sie erhält rangpunkte rang rank points negativ negative zen-bohne zen bean symbol des weisen kaisers sage kings symbol schadensbonus damage bonus weiser kaiser rang verlieren rank loss tot death rechner calculator"
},
{
"id": "events",
"page": "events.html",
"title": "Event Helper",
"description": "Übersicht über alle Events + Hilfetools",
"keywords": [
"event",
"events",
"helper",
"okey",
"tombola",
"treasure",
"schatzsuche",
"underworld",
"unterwelt",
"yutnori",
"kartenspiel",
"anderwelt",
"schnapp den könig",
"seherwettstreit",
"goblin"
],
"category": "tools",
"icon": "https://m2-helper.com/resources/guides/events.png",
"searchText": "event helper übersicht über alle events + hilfetools event events helper okey tombola treasure schatzsuche underworld unterwelt yutnori kartenspiel anderwelt schnapp den könig seherwettstreit goblin"
},
{
"id": "bio-calculator",
"page": "bio.html",
"title": "Bio Akzeleratoren Rechner",
"description": "Berechne optimal deinen Fortschritt bei den Biologen-Quests",
"keywords": [
"bio",
"biologe",
"akzelerator",
"rechner",
"calculator",
"quest"
],
"category": "tools",
"icon": "https://m2-helper.com/resources/accelerator.png",
"searchText": "bio akzeleratoren rechner berechne optimal deinen fortschritt bei den biologen-quests bio biologe akzelerator rechner calculator quest"
},
{
"id": "horse-calculator",
"page": "horse.html",
"title": "Pferdelevel Rechner",
"description": "Berechne Kosten und Pferdefutter für die Verbesserung deines Pferdes",
"keywords": [
"pferd",
"horse",
"level",
"rechner",
"calculator",
"futter"
],
"category": "tools",
"icon": "https://m2-helper.com/resources/Goldenes_Pferdebuch.png",
"searchText": "pferdelevel rechner berechne kosten und pferdefutter für die verbesserung deines pferdes pferd horse level rechner calculator futter"
},
{
"id": "pet-calculator",
"page": "pet.html",
"title": "Petlevel Rechner",
"description": "Tipps, Tricks und Rechner für das Pet-System",
"keywords": [
"pet",
"haustier",
"level",
"rechner",
"calculator"
],
"category": "tools",
"icon": "https://m2-helper.com/resources/Transportbox.png",
"searchText": "petlevel rechner tipps, tricks und rechner für das pet-system pet haustier level rechner calculator"
},
{
"id": "guild-logo",
"page": "guild-logo.html",
"title": "Gildenlogo Editor",
"description": "Konvertiere dein Bild in ein Metin2-kompatibles Gildenlogo",
"keywords": [
"gildenlogo",
"gilde",
"logo",
"tga",
"pixel",
"editor",
"konverter",
"bild"
],
"category": "tools",
"icon": "https://m2-helper.com/resources/guides/gilden-logo.png",
"searchText": "gildenlogo editor konvertiere dein bild in ein metin2-kompatibles gildenlogo gildenlogo gilde logo tga pixel editor konverter bild 16x12 herunterladen pixelart"
},
{
"id": "leveling",
"page": "leveling.html",
"title": "Level Guide",
"description": "Optimale Levelrouten und Tipps für alle Stufen",
"keywords": [
"level",
"leveln",
"leveling",
"exp",
"erfahrung",
"guide",
"route",
"low level",
"mid level",
"high level",
"champion",
"cl1",
"cl10",
"map",
"karte",
"grotte",
"sd2",
"sd3",
"dämonenturm",
"tempel der ochao",
"verwunschener wald",
"zeitriss",
"zr",
"mysteröses dungeon",
"abgrund der gier",
"yohara",
"exp bonus",
"gruppenbonus",
"erfahrungsring",
"trank der weisheit",
"relative exp",
"söldnereinsätze",
"sung mahi"
],
"category": "guides",
"icon": "https://m2-helper.com/resources/exp.png",
"searchText": "level guide optimale levelrouten und tipps für alle stufen level leveln leveling exp erfahrung guide route low level mid level high level champion cl1 cl10 map karte grotte sd2 sd3 dämonenturm tempel der ochao verwunschener wald zeitriss zr mysteröses dungeon abgrund der gier yohara exp bonus gruppenbonus erfahrungsring trank der weisheit relative exp söldnereinsätze sung mahi"
},
{
"id": "dungeons",
"page": "dungeons.html",
"title": "Dungeons",
"description": "Kompakte Guides für alle Dungeons mit Strategien und Belohnungen",
"keywords": [
"dungeon",
"dungeons",
"guide",
"boss",
"instanz",
"pve",
"zodiak",
"spinnenbaroness",
"bruthöhle",
"gildenrun",
"dämonenturm",
"beran-setaou",
"enigma-tempel",
"meley",
"hydra",
"jotun",
"nemere",
"razador",
"zeitriss",
"erweckung",
"schlangenrun",
"alastor",
"balathor"
],
"category": "guides",
"icon": "https://m2-helper.com/resources/guides/Schatzrolle.png",
"searchText": "dungeons kompakte guides für alle dungeons mit strategien und belohnungen dungeon dungeons guide boss instanz pve zodiak spinnenbaroness bruthöhle gildenrun dämonenturm beran-setaou enigma-tempel meley hydra jotun nemere razador zeitriss erweckung schlangenrun alastor balathor"
},
{
"id": "dungeon-zodiac",
"page": "dungeons.html#zodiac",
"title": "Zodiak-Tempel",
"description": "Wochentagabhängiger Dungeon mit 40 Ebenen ab Level 20",
"keywords": [
"zodiak",
"tempel",
"temple",
"animasphäre",
"goldene zodiakschatulle",
"rote zodiakschatulle",
"wochentag",
"ebenen",
"floors"
],
"category": "guides",
"icon": "https://m2-helper.com/resources/guides/dungeons/250px-Wächter_Chen.png",
"searchText": "zodiak-tempel wochentagabhängiger dungeon mit 40 ebenen ab level 20 zodiak tempel temple animasphäre goldene zodiakschatulle rote zodiakschatulle wochentag ebenen floors"
},
{
"id": "dungeon-guildrun",
"page": "dungeons.html#guildrun",
"title": "Palast des Drachenkönig",
"description": "Wöchentliche Dungeons für Gilden ab Level 70",
"keywords": [
"palast",
"drachenkönig",
"gildenrun",
"guild run",
"königsschlüssel",
"tapferkeitsmedaillen",
"gilde",
"wöchentlich",
"medals",
"medaillen"
],
"category": "guides",
"icon": "https://m2-helper.com/resources/guides/dungeons/gildenrun.png",
"searchText": "palast des drachenkönig wöchentliche dungeons für gilden ab level 70 palast drachenkönig gildenrun guild run königsschlüssel tapferkeitsmedaillen gilde wöchentlich medals medaillen"
},
{
"id": "dungeon-spider-baroness",
"page": "dungeons.html#spider-baroness",
"title": "Bruthöhle der Spinnenbaroness",
"description": "Einer der ersten Dungeons ab Level 50 mit Insekten-Rasse",
"keywords": [
"spinne",
"spinnenbaroness",
"baroness",
"spider",
"bruthöhle",
"sd3",
"arachnidenschlüssel",
"pet kitap sandığı",
"teleportation ring",
"passierschein",
"titanenschild",
"insekten"
],
"category": "guides",
"icon": "https://m2-helper.com/resources/guides/dungeons/250px-Spinnenbaroness.png",
"searchText": "bruthöhle der spinnenbaroness einer der ersten dungeons ab level 50 mit insekten-rasse spinne spinnenbaroness baroness spider bruthöhle sd3 arachnidenschlüssel pet kitap sandığı teleportation ring passierschein titanenschild insekten"
},
{
"id": "dungeon-demon-tower",
"page": "dungeons.html#demon-tower",
"title": "Dämonenturm",
"description": "Klassischer Dungeon mit 9 Etagen",
"keywords": [
"dämonenturm",
"demon tower",
"dämonen",
"turm",
"schrumpfkopf",
"shrunken head",
"glas der suche",
"untote",
"undead",
"teufel",
"hwang tempel"
],
"category": "guides",
"icon": "https://m2-helper.com/resources/guides/dungeons/202px-Sensenmann.png",
"searchText": "dämonenturm klassischer dungeon mit 9 etagen dämonenturm demon tower dämonen turm schrumpfkopf shrunken head glas der suche untote undead teufel hwang tempel"
},
{
"id": "dungeon-devils-catacomb",
"page": "dungeons.html#devils-catacomb",
"title": "Teufelskatakomben",
"description": "Nachfolger des Dämonenturms ab Level 75 mit Untote-Rasse",
"keywords": [
"teufelskatakomben",
"devils catacomb",
"teufel",
"katakomben",
"schrumpfkopf",
"titanenschild",
"untote",
"hwang tempel"
],
"category": "guides",
"icon": "https://m2-helper.com/resources/guides/dungeons/250px-Azrael.png",
"searchText": "teufelskatakomben nachfolger des dämonenturms ab level 75 mit untote-rasse teufelskatakomben devils catacomb teufel katakomben schrumpfkopf titanenschild untote hwang tempel"
},
{
"id": "dungeon-beran-setaou",
"page": "dungeons.html#beran-setaou",
"title": "Drache Beran-Setaou",
"description": "Erster lohnenswerter Lowlevel-Dungeon ab Level 75 mit Tiere und Orks-Rassen",
"keywords": [
"beran",
"setaou",
"drache",
"dragon",
"gewundener schlüssel",
"drachenraum-eintritt",
"beran truhe",
"gegenstand verstärken",
"gegenstand verzaubern",
"yang",
"tiere",
"orks",
"animals",
"orcs",
"verbannungshöhle"
],
"category": "guides",
"icon": "https://m2-helper.com/resources/guides/dungeons/Beran-Setaou.png",
"searchText": "drache beran-setaou erster lohnenswerter lowlevel-dungeon ab level 75 mit tiere und orks-rassen beran setaou drache dragon gewundener schlüssel drachenraum-eintritt beran truhe gegenstand verstärken gegenstand verzaubern yang tiere orks animals orcs verbannungshöhle"
},
{
"id": "dungeon-enigma-c",
"page": "dungeons.html#enigmaC",
"title": "Enigma-Tempel C",
"description": "Zufallsdungeon mit wechselndem Ort Level 75-90 mit Rassenlos",
"keywords": [
"enigma",
"tempel",
"temple",
"grad c",
"grade c",
"schatzrolle",
"schatzkiste",
"bonus",
"rassenlos",
"raceless",
"zufällig",
"random"
],
"category": "guides",
"icon": "https://m2-helper.com/resources/guides/dungeons/Schatzrolle_(Grad_C).png",
"searchText": "enigma-tempel c zufallsdungeon mit wechselndem ort level 75-90 mit rassenlos enigma tempel temple grad c grade c schatzrolle schatzkiste bonus rassenlos raceless zufällig random"
},
{
"id": "dungeon-enigma-b",
"page": "dungeons.html#enigmaB",
"title": "Enigma-Tempel B",
"description": "Zufallsdungeon mit wechselndem Ort Level 90-120 mit Rassenlos",
"keywords": [
"enigma",
"tempel",
"temple",
"grad b",
"grade b",
"schatzrolle",
"schatzkiste",
"bonus",
"rassenlos",
"raceless",
"zufällig",
"random"
],
"category": "guides",
"icon": "https://m2-helper.com/resources/guides/dungeons/Schatzrolle_(Grad_B).png",
"searchText": "enigma-tempel b zufallsdungeon mit wechselndem ort level 90-120 mit rassenlos enigma tempel temple grad b grade b schatzrolle schatzkiste bonus rassenlos raceless zufällig random"
},
{
"id": "dungeon-enigma-a",
"page": "dungeons.html#enigmaA",
"title": "Enigma-Tempel A",
"description": "Zufallsdungeon mit wechselndem Ort ab Champion Level 1 mit Rassenlos",
"keywords": [
"enigma",
"tempel",
"temple",
"grad a",
"grade a",
"schatzrolle",
"schatzkiste",
"bonus",
"rassenlos",
"raceless",
"zufällig",
"random",
"champion",
"pferde skills",
"horse skills"
],
"category": "guides",
"icon": "https://m2-helper.com/resources/guides/dungeons/Schatzrolle_(Grad_A).png",
"searchText": "enigma-tempel a zufallsdungeon mit wechselndem ort ab champion level 1 mit rassenlos enigma tempel temple grad a grade a schatzrolle schatzkiste bonus rassenlos raceless zufällig random champion pferde skills horse skills"
},
{
"id": "dungeon-serpent-temple",
"page": "dungeons.html#serpent-temple",
"title": "Schlangentempel",
"description": "Liefert Materialien für Schlangenrüstung ab Champion Level 1 mit Tiere, Esoterische und Halbmenschen-Rassen",
"keywords": [
"schlangentempel",
"serpent temple",
"schlange",
"yilad übergang",
"schlangenschatz",
"schlangenpelz",
"tiere",
"animals",
"esoterische",
"esoteric",
"halbmenschen",
"half-humans",
"yohara",
"feuer",
"wasser",
"erde",
"wind",
"blitz"
],
"category": "guides",
"icon": "https://m2-helper.com/resources/guides/dungeons/250px-Schlangenkönigin_Nethis_(Erde).png",
"searchText": "schlangentempel liefert materialien für schlangenrüstung ab champion level 1 mit tiere, esoterische und halbmenschen-rassen schlangentempel serpent temple schlange yilad übergang schlangenschatz schlangenpelz tiere animals esoterische esoteric halbmenschen half-humans yohara feuer wasser erde wind blitz"
},
{
"id": "dungeon-alastor",
"page": "dungeons.html#alastor",
"title": "Alastor (leicht / schwer)",
"description": "Liefert Materialien für Schlangenwaffen ab Champion Level 1 mit Tiere, Esoterische und Halbmenschen-Rassen",
"keywords": [
"alastor",
"nordwind tiefen",
"gefrorener schlüssel",
"weißer drachentruhe",
"tiere",
"animals",
"esoterische",
"esoteric",
"halbmenschen",
"half-humans",
"yohara",
"wasser",
"eis"
],
"category": "guides",
"icon": "https://m2-helper.com/resources/guides/dungeons/alastor.png",
"searchText": "alastor (leicht / schwer) liefert materialien für schlangenwaffen ab champion level 1 mit tiere, esoterische und halbmenschen-rassen alastor nordwind tiefen gefrorener schlüssel weißer drachentruhe tiere animals esoterische esoteric halbmenschen half-humans yohara wasser eis"
},
{
"id": "dungeon-balathor",
"page": "dungeons.html#balathor",
"title": "Balathors Krypta",
"description": "Gildendungeon für fortgeschrittene Spieler ab Champion Level 4 mit Esoterische und Halbmenschen-Rassen",
"keywords": [
"balathor",
"grab",
"tomb",
"berg sohan",
"balathors frosttruhe",
"esoterische",
"esoteric",
"halbmenschen",
"half-humans",
"gilde",
"guild",
"yohara",
"eis"
],
"category": "guides",
"icon": "https://m2-helper.com/resources/guides/dungeons/balathor.png",
"searchText": "balathors krypta gildendungeon für fortgeschrittene spieler ab champion level 4 mit esoterische und halbmenschen-rassen balathor grab tomb berg sohan balathors frosttruhe esoterische esoteric halbmenschen half-humans gilde guild yohara eis"
},
{
"id": "dungeon-meley-group",
"page": "dungeons.html#meley-group",
"title": "Meleys Hort - Gruppe",
"description": "Gruppendungeon nur für Gaya ab Level 75 mit Rassenlos",
"keywords": [
"meley",
"meleys",
"hort",
"lair",
"gruppe",
"group",
"gaya",
"schmuckstein",
"gem",
"feuerlande",
"fire lands",
"rassenlos",
"raceless",
"feuer"
],
"category": "guides",
"icon": "https://m2-helper.com/resources/guides/dungeons/meley.png",
"searchText": "meleys hort - gruppe gruppendungeon nur für gaya ab level 75 mit rassenlos meley meleys hort lair gruppe group gaya schmuckstein gem feuerlande fire lands rassenlos raceless feuer"
},
{
"id": "dungeon-meley-guild",
"page": "dungeons.html#meley-guild",
"title": "Meleys Hort - Gilde",
"description": "Gildendungeon für Level 90 Spieler mit Rassenlos",
"keywords": [
"meley",
"meleys",
"hort",
"lair",
"gilde",
"guild",
"königin meley truhe",
"drachenwächter truhe",
"feuerlande",
"fire lands",
"rassenlos",
"raceless",
"feuer",
"ninja"
],
"category": "guides",
"icon": "https://m2-helper.com/resources/guides/dungeons/meley.png",
"searchText": "meleys hort - gilde gildendungeon für level 90 spieler mit rassenlos meley meleys hort lair gilde guild königin meley truhe drachenwächter truhe feuerlande fire lands rassenlos raceless feuer ninja"
},
{
"id": "dungeon-razador",
"page": "dungeons.html#razador",
"title": "Rote Drachenfestung / Razador",
"description": "Endgame-Dungeon für erfahrene Spieler ab Level 100 mit Teufel-Rasse",
"keywords": [
"razador",
"rote drachenfestung",
"red dragon fortress",
"razador truhe",
"feuerlande",
"fire lands",
"teufel",
"devils",
"feuer",
"dunkelheit",
"dunkle säule",
"dark pillar",
"morun"
],
"category": "guides",
"icon": "https://m2-helper.com/resources/guides/dungeons/250px-Razador.png",
"searchText": "rote drachenfestung / razador endgame-dungeon für erfahrene spieler ab level 100 mit teufel-rasse razador rote drachenfestung red dragon fortress razador truhe feuerlande fire lands teufel devils feuer dunkelheit dunkle säule dark pillar morun"
},
{
"id": "dungeon-nemere",
"page": "dungeons.html#nemere",
"title": "Nemeres Warte",
"description": "Zählt zu den ersten lohnenswerten Dungeons ab Level 100 mit Esoterische-Rasse",
"keywords": [
"nemere",
"nemeres warte",
"nemeres watchtower",
"nemere truhe",
"berg sohan",
"mount sohan",
"esoterische",
"esoteric",
"eis",
"ninja",
"drachenschamane",
"dragon shaman"
],
"category": "guides",
"icon": "https://m2-helper.com/resources/guides/dungeons/250px-Nemere.png",
"searchText": "nemeres warte zählt zu den ersten lohnenswerten dungeons ab level 100 mit esoterische-rasse nemere nemeres warte nemeres watchtower nemere truhe berg sohan mount sohan esoterische esoteric eis ninja drachenschamane dragon shaman"
},
{
"id": "dungeon-time-rift",
"page": "dungeons.html#time-rift",
"title": "Zeitriss Dungeons",
"description": "Wird nur zum Leveln verwendet ab Level 110 mit Tiere, Orks, Teufel und Esoterische-Rassen",
"keywords": [
"zeitriss",
"time rift",
"taschenuhr",
"pocket watch",
"buch der erweckung",
"book of awakening",
"plateau der illusionen",
"tiere",
"animals",
"orks",
"orcs",
"teufel",
"devils",
"esoterische",
"esoteric",
"feuer",
"wasser",
"erde",
"blitz",
"dunkelheit",
"eis"
],
"category": "guides",
"icon": "https://m2-helper.com/resources/guides/dungeons/erweckung-zeitriss.png",
"searchText": "zeitriss dungeons wird nur zum leveln verwendet ab level 110 mit tiere, orks, teufel und esoterische-rassen zeitriss time rift taschenuhr pocket watch buch der erweckung book of awakening plateau der illusionen tiere animals orks orcs teufel devils esoterische esoteric feuer wasser erde blitz dunkelheit eis"
},
{
"id": "dungeon-redux",
"page": "dungeons.html#redux",
"title": "Erweckungs Dungeons",
"description": "Herausfordernde Erweckungsdungeons ab Level 110 mit Tiere, Orks, Teufel und Esoterische-Rassen",
"keywords": [
"erweckung",
"awakening",
"redux",
"buch der erweckung",
"book of awakening",
"truhe der erweckung",
"ew beran",
"ew jotun",
"ew razador",
"ew nemere",
"plateau der illusionen",
"tiere",
"animals",
"orks",
"orcs",
"teufel",
"devils",
"esoterische",
"esoteric",
"feuer",
"wasser",
"erde",
"blitz",
"dunkelheit",
"eis"
],
"category": "guides",
"icon": "https://m2-helper.com/resources/guides/dungeons/erweckung-zeitriss.png",
"searchText": "erweckungs dungeons herausfordernde erweckungsdungeons ab level 110 mit tiere, orks, teufel und esoterische-rassen erweckung awakening redux buch der erweckung book of awakening truhe der erweckung ew beran ew jotun ew razador ew nemere plateau der illusionen tiere animals orks orcs teufel devils esoterische esoteric feuer wasser erde blitz dunkelheit eis"
},
{
"id": "dungeon-hydra",
"page": "dungeons.html#hydra",
"title": "Schiffsverteidigung / Hydra",
"description": "Sehr lukrativer Dungeon ab Level 90 mit Tiere-Rasse",
"keywords": [
"hydra",
"schiffsverteidigung",
"ship defense",
"kap drachenfeuer",
"passierschein",
"hydras truhe",
"nessie ei",
"ebenholzkasten",
"gegenstand verzaubern",
"gegenstand verstärken",
"buch der erweckung",
"tiere",
"animals",
"wasser"
],
"category": "guides",
"icon": "https://m2-helper.com/resources/guides/dungeons/250px-Hydra.png",
"searchText": "schiffsverteidigung / hydra sehr lukrativer dungeon ab level 90 mit tiere-rasse hydra schiffsverteidigung ship defense kap drachenfeuer passierschein hydras truhe nessie ei ebenholzkasten gegenstand verzaubern gegenstand verstärken buch der erweckung tiere animals wasser"
},
{
"id": "dungeon-jotun",
"page": "dungeons.html#jotun",
"title": "Erebos / Jotun Thrym",
"description": "Hat die höchste Anforderung an die Gruppengröße ab Level 95 mit Tiere und Esoterische-Rassen",
"keywords": [
"erebos",
"jotun",
"thrym",
"verzauberter wald",
"enchanted forest",
"stein der dryaden",
"bagjanamu truhe",
"jotun thrym truhe",
"yang",
"tiere",
"animals",
"esoterische",
"esoteric",
"erde",
"wind"
],
"category": "guides",
"icon": "https://m2-helper.com/resources/guides/dungeons/250px-Jotun_Thrym.png",
"searchText": "erebos / jotun thrym hat die höchste anforderung an die gruppengröße ab level 95 mit tiere und esoterische-rassen erebos jotun thrym verzauberter wald enchanted forest stein der dryaden bagjanamu truhe jotun thrym truhe yang tiere animals esoterische esoteric erde wind"
},
{
"id": "bazar",
"page": "bazar.html",
"title": "Online Bazar",
"description": "Finde Equipment von allen Servern",
"keywords": [
"bazar",
"markt",
"equipment",
"item",
"suche",
"handel"
],
"category": "tools",
"icon": "https://m2-helper.com/resources/bazar/Glas_des_Handels.png",
"searchText": "online bazar finde equipment von allen servern bazar markt equipment item suche handel"
},
{
"id": "mercenaries",
"page": "mercenaries.html",
"title": "Söldner-System",
"description": "Guide zum Söldner-System – Söldner leveln, Spezialisierungen, Fähigkeiten und Belohnungen",
"keywords": [
"söldner", "söldner-system", "söldnersystem", "mercenary", "rekrutieren",
"söldnerlizenz", "lizenz", "lehrender", "trainer", "leveln", "ausbilden",
"ausdauer", "champion level", "mission", "einsatz",
"normaler", "geschickter", "starker", "erfahrener", "sammelnder", "glücklicher",
"späher", "kämpfer", "retter", "sammler", "glückspilz",
"spezialisierung", "fähigkeit",
"riskanter vorteil", "erhöhe erfolgschance", "verringerte verletzungschance",
"verringere die einsatzdauer", "extra championlevel-exp",
"erfolgschance", "verletzungsrisiko", "einsatzdauer", "belohnung",
"söldnerheilung", "donganebene", "yohara-kommandeur", "sung mahis höllenturm"
],
"category": "guides",
"icon": "https://m2-helper.com/resources/guides/söldner.png",
"searchText": "söldner-system guide rekrutieren söldnerlizenz lehrender trainer leveln ausdauer champion level normaler geschickter starker erfahrener sammelnder glücklicher späher kämpfer retter sammler glückspilz spezialisierung fähigkeit riskanter vorteil erhöhe erfolgschance verringerte verletzungschance extra championlevel-exp erfolgschance belohnung"
}
],
"en": [
{
"id": "home",
"page": "index.html",
"title": "Home",
"description": "Your central hub for wiki, tools, and community around Metin2",
"keywords": [
"home",
"start",
"main"
],
"category": "main",
"icon": "https://m2-helper.com/resources/söldner_2.png",
"searchText": "home your central hub for wiki, tools, and community around metin2 home start main"
},
{
"id": "guides",
"page": "guides.html",
"title": "Guides",
"description": "Comprehensive tutorials and strategies for all areas",
"keywords": [
"guide",
"tutorial",
"help"
],
"category": "guides",
"icon": "https://m2-helper.com/resources/guides/quest.png",
"searchText": "guides comprehensive tutorials and strategies for all areas guide tutorial help"
},
{
"id": "server-guide",
"page": "server.html",
"title": "Server Guide",
"description": "Find the right server for you",
"keywords": [
"server",
"beginner",
"choice",
"comparison",
"which"
],
"category": "guides",
"icon": "https://m2-helper.com/resources/guides/server.png",
"searchText": "server guide find the right server for you server beginner choice comparison which"
},
{
"id": "dragon-alchemy",
"page": "dragon-alchemy.html",
"title": "Dragon Stone Alchemy",
"description": "Complete guide to dragon stone alchemy and stone improvement",
"keywords": [
"dragon",
"stone",
"alchemy",
"dsa",
"upgrade",
"system",
"level",
"class",
"purity",
"dragon bean",
"dragon flame",
"raw",
"cut",
"rare",
"antique",
"legendary",
"mythical",
"matte",
"clear",
"flawless",
"brilliant",
"excellent",
"alchemist",
"time tongs",
"dragon tongs+",
"time elixir",
"calculator",
"elixir of time",
"diamond",
"amethyst",
"onyx",
"garnet",
"sapphire",
"jade",
"ruby"
],
"category": "systems",
"icon": "https://m2-helper.com/resources/guides/alchemy.png",
"searchText": "dragon stone alchemy complete guide to dragon stone alchemy and stone improvement dragon stone alchemy dsa upgrade system level class purity dragon bean dragon flame raw cut rare antique legendary mythical matte clear flawless brilliant excellent alchemist time tongs dragon tongs+ time elixir calculator elixir of time diamond amethyst onyx garnet sapphire jade ruby"
},
{
"id": "echoes-of-power",
"page": "echoes-of-power.html",
"title": "Echoes of Power",
"description": "Guide to Echoes of Power system and rewards",
"keywords": [
"echoes",
"power",
"reward",
"system",
"echo of strength",
"echo of skill",
"damage"
],
"category": "systems",
"icon": "https://m2-helper.com/resources/guides/Echos_der_Macht.png",
"searchText": "echoes of power guide to echoes of power system and rewards echoes power reward system echo of strength echo of skill damage"
},
{
"id": "metin-plus",
"page": "metin-plus.html",
"title": "Metin+",
"description": "Guide to Metin+ system and its exclusive features",
"keywords": [
"metin+",
"metin plus",
"premium",
"feature",
"system",
"challenges",
"rewards",
"raffle"
],
"category": "systems",
"icon": "https://m2-helper.com/resources/guides/m2+.png",
"searchText": "metin+ guide to metin+ system and its exclusive features metin+ metin plus premium feature system challenges rewards raffle"
},
{
"id": "donation-guild",
"page": "donation-guild.html",
"title": "Donation Guild",
"description": "Clear tool for tracking a donation guild",
"keywords": [
"donation",
"guild",
"tracker",
"management",
"calculator",
"medals of bravery"
],
"category": "miscellaneous",
"icon": "https://m2-helper.com/resources/guides/server2.png",
"searchText": "donation guild clear tool for tracking a donation guild donation guild tracker management calculator medals of bravery"
},
{
"id": "miscellaneous",
"page": "miscellaneous.html",
"title": "Miscellaneous",
"description": "More helpful guides and tips for Metin2",
"keywords": [
"miscellaneous",
"tips",
"tricks",
"aura",
"robe",
"outfit",
"gaya",
"gem",
"rank",
"points",
"faq",
"frequently",
"questions",
"upgrade",
"chance",
"dragon",
"stone",
"bonus",
"drop",
"soul",
"stone",
"calculator"
],
"category": "miscellaneous",
"icon": "https://m2-helper.com/resources/guides/scroll_open.png",
"searchText": "miscellaneous more helpful guides and tips for metin2 miscellaneous tips tricks aura robe outfit gaya gem rank points faq frequently questions upgrade chance dragon stone bonus drop soul stone calculator"
},
{
"id": "loot-filter",
"page": "loot-filter.html",
"title": "Loot-Filter Settings",
"description": "Find the right category for a searched item",
"keywords": [
"loot filter",
"lootfilter",
"loot",
"filter",
"items",
"settings",
"drop"
],
"category": "tools",
"icon": "https://m2-helper.com/resources/guides/other/Loot-Pass.png",
"searchText": "loot-filter settings find the right category for a searched item loot filter lootfilter loot filter items settings drop"
},
{
"id": "timer",
"page": "timer.html",
"title": "Timer",
"description": "Create individual timers and use them with your teammates",
"keywords": [
"timer",
"boss",
"raid",
"group",
"channel",
"spawn",
"respawn",
"coordination",
"team",
"realtime",
"synchronization",
"teammates",
"individual"
],
"category": "tools",
"icon": "https://m2-helper.com/resources/accelerator.png",
"searchText": "timer create individual timers and use them with your teammates timer boss raid group channel spawn respawn coordination team realtime synchronization teammates individual"
},
{
"id": "aura-calculator",
"page": "miscellaneous.html#aura-calculator",
"title": "Aura Robe Calculator",
"description": "Calculate costs and resources for your aura robe leveling",
"keywords": [
"aura",
"robe",
"outfit",
"calculator",
"fire rune",
"level",
"cost",
"resources",
"radiant aura robe",
"common aura robe",
"ice rune",
"aura of power"
],
"category": "tools",
"icon": "https://m2-helper.com/resources/guides/other/Strahlendes_Auragewand.png",
"searchText": "aura robe calculator calculate costs and resources for your aura robe leveling aura robe outfit calculator fire rune level cost resources radiant aura robe common aura robe ice rune aura of power"
},
{
"id": "gaya-calculator",
"page": "miscellaneous.html#gaya-calculator",
"title": "Gaya Calculator",
"description": "Calculate how much Gaya you get from gems and spirit stone bundles",
"keywords": [
"gaya",
"calculator",
"gem",
"glimmerstone",
"spirit stone bundle",
"meleys lair",
"meley",
"materials",
"resources"
],
"category": "tools",
"icon": "https://m2-helper.com/resources/guides/other/Gaya.png",
"searchText": "gaya calculator calculate how much gaya you get from gems and spirit stone bundles gaya calculator gem glimmerstone spirit stone bundle meleys lair meley materials resources"
},
{
"id": "rank-points",
"page": "miscellaneous.html#rank-points",
"title": "Rank Points Guide",
"description": "Everything about the rank points system and how to gain them",
"keywords": [
"rank",
"points",
"negative",
"zen bean",
"sage kings symbol",
"damage bonus",
"sage king",
"rank loss",
"death",
"calculator"
],
"category": "guides",
"icon": "https://m2-helper.com/resources/guides/other/Zen-Bohne.png",
"searchText": "rank points guide everything about the rank points system and how to gain them rank points negative zen bean sage kings symbol damage bonus sage king rank loss death calculator"
},
{
"id": "events",
"page": "events.html",
"title": "Event Helper",
"description": "Overview for all events + help tools",
"keywords": [
"event",
"events",
"helper",
"okey",
"tombola",
"treasure",
"hunt",
"underworld",
"yutnori",
"card",
"game",
"catch the king",
"seer contest"
],
"category": "tools",
"icon": "https://m2-helper.com/resources/guides/events.png",
"searchText": "event helper overview for all events + help tools event events helper okey tombola treasure hunt underworld yutnori card game catch the king seer contest"
},
{
"id": "bio-calculator",
"page": "bio.html",
"title": "Bio Accelerators Calculator",
"description": "Optimally calculate your progress in the biologist quests",
"keywords": [
"bio",
"biologist",
"accelerator",
"calculator",
"quest"
],
"category": "tools",
"icon": "https://m2-helper.com/resources/accelerator.png",
"searchText": "bio accelerators calculator optimally calculate your progress in the biologist quests bio biologist accelerator calculator quest"
},
{
"id": "horse-calculator",
"page": "horse.html",
"title": "Horse Level Calculator",
"description": "Calculate costs and horse feed for your horse leveling",
"keywords": [
"horse",
"level",
"calculator",
"feed"
],
"category": "tools",
"icon": "https://m2-helper.com/resources/Goldenes_Pferdebuch.png",
"searchText": "horse level calculator calculate costs and horse feed for your horse leveling horse level calculator feed"
},
{
"id": "pet-calculator",
"page": "pet.html",
"title": "Pet Level Calculator",
"description": "Tips, tricks, and calculator for the pet system",
"keywords": [
"pet",
"level",
"calculator",
"tips"
],
"category": "tools",
"icon": "https://m2-helper.com/resources/Transportbox.png",
"searchText": "pet level calculator tips, tricks, and calculator for the pet system pet level calculator tips"
},
{
"id": "guild-logo",
"page": "guild-logo.html",
"title": "Guild Logo Editor",
"description": "Convert your image to a Metin2-compatible guild logo",
"keywords": [
"guild logo",
"guild",
"logo",
"tga",
"pixel",
"editor",
"converter",
"image"
],
"category": "tools",
"icon": "https://m2-helper.com/resources/guides/gilden-logo.png",
"searchText": "guild logo editor convert your image to a metin2-compatible guild logo guild logo tga pixel editor converter image 16x12 download pixelart"
},
{
"id": "leveling",
"page": "leveling.html",
"title": "Level Guide",
"description": "Optimal leveling routes and experience tips for all levels",
"keywords": [
"level",
"leveling",
"exp",
"experience",
"guide",
"route",
"low level",
"mid level",
"high level",
"champion",
"cl1",
"cl10",
"map",
"grotto",
"sd2",
"sd3",
"demon tower",
"temple of ochao",
"enchanted forest",
"time rift",
"tr",
"mysterious dungeon",
"depths of greed",
"yohara",
"exp bonus",
"group bonus",
"experience ring",
"potion of wisdom",
"relative exp",
"mercenary missions",
"sung mahi"
],
"category": "guides",
"icon": "https://m2-helper.com/resources/exp.png",
"searchText": "level guide optimal leveling routes and experience tips for all levels level leveling exp experience guide route low level mid level high level champion cl1 cl10 map grotto sd2 sd3 demon tower temple of ochao enchanted forest time rift tr mysterious dungeon depths of greed yohara exp bonus group bonus experience ring potion of wisdom relative exp mercenary missions sung mahi"
},
{
"id": "dungeons",
"page": "dungeons.html",
"title": "Dungeons",
"description": "Compact guides for all dungeons with strategies and rewards",
"keywords": [
"dungeon",
"dungeons",
"guide",
"boss",
"instance",
"pve",
"zodiac",
"spider baroness",
"guild run",
"demon tower",
"beran-setaou",
"enigma temple",
"meley",
"hydra",
"jotun",
"nemere",
"razador",
"time rift",
"awakening",
"snake run",
"alastor",
"balathor"
],
"category": "guides",
"icon": "https://m2-helper.com/resources/guides/Schatzrolle.png",
"searchText": "dungeons compact guides for all dungeons with strategies and rewards dungeon dungeons guide boss instance pve zodiac spider baroness guild run demon tower beran-setaou enigma temple meley hydra jotun nemere razador time rift awakening snake run alastor balathor"
},
{
"id": "dungeon-zodiac",
"page": "dungeons.html#zodiac",
"title": "Zodiac Temple",
"description": "Weekday-dependent dungeon with 40 floors from Level 20",
"keywords": [
"zodiac",
"temple",
"anima sphere",
"golden zodiac casket",
"red zodiac casket",
"weekday",
"floors"
],
"category": "guides",
"icon": "https://m2-helper.com/resources/guides/dungeons/250px-Wächter_Chen.png",
"searchText": "zodiac temple weekday-dependent dungeon with 40 floors from level 20 zodiac temple anima sphere golden zodiac casket red zodiac casket weekday floors"
},
{
"id": "dungeon-guildrun",
"page": "dungeons.html#guildrun",
"title": "Palace of the Dragon King",
"description": "Weekly dungeons for guilds from Level 70",
"keywords": [
"palace",
"dragon king",
"guild run",
"kings key",
"medals of bravery",
"guild",
"weekly"
],
"category": "guides",
"icon": "https://m2-helper.com/resources/guides/dungeons/gildenrun.png",
"searchText": "palace of the dragon king weekly dungeons for guilds from level 70 palace dragon king guild run kings key medals of bravery guild weekly"
},
{
"id": "dungeon-spider-baroness",
"page": "dungeons.html#spider-baroness",
"title": "Spider Baroness Brood",
"description": "One of the first dungeons from Level 50 with insects race",
"keywords": [
"spider",
"baroness",
"brood",
"arachnid key",
"pet book chest",
"teleportation ring",
"pass",
"titan shield",
"insects"
],
"category": "guides",
"icon": "https://m2-helper.com/resources/guides/dungeons/250px-Spinnenbaroness.png",
"searchText": "spider baroness brood one of the first dungeons from level 50 with insects race spider baroness brood arachnid key pet book chest teleportation ring pass titan shield insects"
},
{
"id": "dungeon-demon-tower",
"page": "dungeons.html#demon-tower",
"title": "Demon Tower",
"description": "Classic dungeon with 9 floors from Level 40 with undead race",
"keywords": [
"demon",
"tower",
"shrunken head",
"glass of search",
"undead",
"devils",
"hwang temple"
],
"category": "guides",
"icon": "https://m2-helper.com/resources/guides/dungeons/202px-Sensenmann.png",
"searchText": "demon tower classic dungeon with 9 floors from level 40 with undead race demon tower shrunken head glass of search undead devils hwang temple"
},
{
"id": "dungeon-devils-catacomb",
"page": "dungeons.html#devils-catacomb",
"title": "Devils Catacomb",
"description": "Successor to the Demon Tower from Level 75 with undead race",
"keywords": [
"devils",
"catacomb",
"shrunken head",
"titan shield",
"undead",
"hwang temple"
],
"category": "guides",
"icon": "https://m2-helper.com/resources/guides/dungeons/250px-Azrael.png",
"searchText": "devils catacomb successor to the demon tower from level 75 with undead race devils catacomb shrunken head titan shield undead hwang temple"
},
{
"id": "dungeon-beran-setaou",
"page": "dungeons.html#beran-setaou",
"title": "Dragon Beran-Setaou",
"description": "First worthwhile low-level dungeon from Level 75 with animals and orcs races",
"keywords": [
"beran",
"setaou",
"dragon",
"twisted key",
"dragon room entry",
"beran chest",
"upgrade item",
"enchant item",
"yang",
"animals",
"orcs",
"exile cave"
],
"category": "guides",
"icon": "https://m2-helper.com/resources/guides/dungeons/Beran-Setaou.png",
"searchText": "dragon beran-setaou first worthwhile low-level dungeon from level 75 with animals and orcs races beran setaou dragon twisted key dragon room entry beran chest upgrade item enchant item yang animals orcs exile cave"
},
{
"id": "dungeon-enigma-c",
"page": "dungeons.html#enigmaC",
"title": "Enigma Temple C",
"description": "Random dungeon with changing location Level 75-90 with raceless",
"keywords": [
"enigma",
"temple",
"grade c",
"treasure scroll",
"treasure chest",
"bonus",
"raceless",
"random"
],
"category": "guides",
"icon": "https://m2-helper.com/resources/guides/dungeons/Schatzrolle_(Grad_C).png",
"searchText": "enigma temple c random dungeon with changing location level 75-90 with raceless enigma temple grade c treasure scroll treasure chest bonus raceless random"
},
{
"id": "dungeon-enigma-b",
"page": "dungeons.html#enigmaB",
"title": "Enigma Temple B",
"description": "Random dungeon with changing location Level 90-120 with raceless",
"keywords": [
"enigma",
"temple",
"grade b",
"treasure scroll",
"treasure chest",
"bonus",
"raceless",
"random"
],
"category": "guides",
"icon": "https://m2-helper.com/resources/guides/dungeons/Schatzrolle_(Grad_B).png",
"searchText": "enigma temple b random dungeon with changing location level 90-120 with raceless enigma temple grade b treasure scroll treasure chest bonus raceless random"
},
{
"id": "dungeon-enigma-a",
"page": "dungeons.html#enigmaA",
"title": "Enigma Temple A",
"description": "Random dungeon with changing location from Champion Level 1 with raceless",
"keywords": [
"enigma",
"temple",
"grade a",
"treasure scroll",
"treasure chest",
"bonus",
"raceless",
"random",
"champion",
"horse skills"
],
"category": "guides",
"icon": "https://m2-helper.com/resources/guides/dungeons/Schatzrolle_(Grad_A).png",
"searchText": "enigma temple a random dungeon with changing location from champion level 1 with raceless enigma temple grade a treasure scroll treasure chest bonus raceless random champion horse skills"
},
{
"id": "dungeon-serpent-temple",
"page": "dungeons.html#serpent-temple",
"title": "Serpent Temple",
"description": "Provides materials for snake armor from Champion Level 1 with animals, esoteric and half-humans races",
"keywords": [
"serpent",
"temple",
"snake",
"yilad passage",
"snake treasure",
"snake fur",
"animals",
"esoteric",
"half-humans",
"yohara",
"fire",
"water",
"earth",
"wind",
"lightning"
],
"category": "guides",
"icon": "https://m2-helper.com/resources/guides/dungeons/250px-Schlangenkönigin_Nethis_(Erde).png",
"searchText": "serpent temple provides materials for snake armor from champion level 1 with animals, esoteric and half-humans races serpent temple snake yilad passage snake treasure snake fur animals esoteric half-humans yohara fire water earth wind lightning"
},
{
"id": "dungeon-alastor",
"page": "dungeons.html#alastor",
"title": "Alastor (easy / hard)",
"description": "Provides materials for snake weapons from Champion Level 1 with animals, esoteric and half-humans races",
"keywords": [
"alastor",
"north wind depths",
"frozen key",
"white dragon chest",
"animals",
"esoteric",
"half-humans",
"yohara",
"water",
"ice"
],
"category": "guides",
"icon": "https://m2-helper.com/resources/guides/dungeons/alastor.png",
"searchText": "alastor (easy / hard) provides materials for snake weapons from champion level 1 with animals, esoteric and half-humans races alastor north wind depths frozen key white dragon chest animals esoteric half-humans yohara water ice"
},
{
"id": "dungeon-balathor",
"page": "dungeons.html#balathor",
"title": "Balathors Tomb",
"description": "Guild dungeon for advanced players from Champion Level 4 with esoteric and half-humans races",
"keywords": [
"balathor",
"tomb",
"mount sohan",
"balathors frost chest",
"esoteric",
"half-humans",
"guild",
"yohara",
"ice"
],
"category": "guides",
"icon": "https://m2-helper.com/resources/guides/dungeons/balathor.png",
"searchText": "balathors tomb guild dungeon for advanced players from champion level 4 with esoteric and half-humans races balathor tomb mount sohan balathors frost chest esoteric half-humans guild yohara ice"
},
{
"id": "dungeon-meley-group",
"page": "dungeons.html#meley-group",
"title": "Meleys Lair - Group",
"description": "Group dungeon only for Gaya from Level 75 with raceless",
"keywords": [
"meley",
"meleys",
"lair",
"group",
"gaya",
"gem",
"fire lands",
"raceless",
"fire"
],
"category": "guides",
"icon": "https://m2-helper.com/resources/guides/dungeons/meley.png",
"searchText": "meleys lair - group group dungeon only for gaya from level 75 with raceless meley meleys lair group gaya gem fire lands raceless fire"
},
{
"id": "dungeon-meley-guild",
"page": "dungeons.html#meley-guild",
"title": "Meleys Lair - Guild",
"description": "Guild dungeon for Level 90 players with raceless",
"keywords": [
"meley",
"meleys",
"lair",
"guild",
"queen meley chest",
"dragon guardian chest",
"fire lands",
"raceless",
"fire",
"ninja"
],
"category": "guides",
"icon": "https://m2-helper.com/resources/guides/dungeons/meley.png",
"searchText": "meleys lair - guild guild dungeon for level 90 players with raceless meley meleys lair guild queen meley chest dragon guardian chest fire lands raceless fire ninja"
},
{
"id": "dungeon-razador",
"page": "dungeons.html#razador",
"title": "Red Dragon Fortress / Razador",
"description": "Endgame dungeon for experienced players from Level 100 with devils race",
"keywords": [
"razador",
"red dragon fortress",
"razador chest",
"fire lands",
"devils",
"fire",
"darkness",
"dark pillar",
"morun"
],
"category": "guides",
"icon": "https://m2-helper.com/resources/guides/dungeons/250px-Razador.png",
"searchText": "red dragon fortress / razador endgame dungeon for experienced players from level 100 with devils race razador red dragon fortress razador chest fire lands devils fire darkness dark pillar morun"
},
{
"id": "dungeon-nemere",
"page": "dungeons.html#nemere",
"title": "Nemeres Watchtower",
"description": "Counts among the first worthwhile dungeons from Level 100 with esoteric race",
"keywords": [
"nemere",
"nemeres watchtower",
"nemere chest",
"mount sohan",
"esoteric",
"ice",
"ninja",
"dragon shaman"
],
"category": "guides",
"icon": "https://m2-helper.com/resources/guides/dungeons/250px-Nemere.png",
"searchText": "nemeres watchtower counts among the first worthwhile dungeons from level 100 with esoteric race nemere nemeres watchtower nemere chest mount sohan esoteric ice ninja dragon shaman"
},
{
"id": "dungeon-time-rift",
"page": "dungeons.html#time-rift",
"title": "Time Rift Dungeons",
"description": "Used only for leveling from Level 110 with animals, orcs, devils and esoteric races",
"keywords": [
"time rift",
"pocket watch",
"book of awakening",
"plateau of illusions",
"animals",
"orcs",
"devils",
"esoteric",
"fire",
"water",
"earth",
"lightning",
"darkness",
"ice"
],
"category": "guides",
"icon": "https://m2-helper.com/resources/guides/dungeons/erweckung-zeitriss.png",
"searchText": "time rift dungeons used only for leveling from level 110 with animals, orcs, devils and esoteric races time rift pocket watch book of awakening plateau of illusions animals orcs devils esoteric fire water earth lightning darkness ice"
},
{
"id": "dungeon-redux",
"page": "dungeons.html#redux",
"title": "Awakening Dungeons",
"description": "Challenging awakening dungeons from Level 110 with animals, orcs, devils and esoteric races",
"keywords": [
"awakening",
"redux",
"book of awakening",
"chest of awakening",
"aw beran",
"aw jotun",
"aw razador",
"aw nemere",
"plateau of illusions",
"animals",
"orcs",
"devils",
"esoteric",
"fire",
"water",
"earth",
"lightning",
"darkness",
"ice"
],
"category": "guides",
"icon": "https://m2-helper.com/resources/guides/dungeons/erweckung-zeitriss.png",
"searchText": "awakening dungeons challenging awakening dungeons from level 110 with animals, orcs, devils and esoteric races awakening redux book of awakening chest of awakening aw beran aw jotun aw razador aw nemere plateau of illusions animals orcs devils esoteric fire water earth lightning darkness ice"
},
{
"id": "dungeon-hydra",
"page": "dungeons.html#hydra",
"title": "Ship Defense / Hydra",
"description": "Very lucrative dungeon from Level 90 with animals race",
"keywords": [
"hydra",
"ship defense",
"cape dragonfire",
"pass",
"hydra chest",
"nessie egg",
"ebony box",
"enchant item",
"upgrade item",
"book of awakening",
"animals",
"water"
],
"category": "guides",
"icon": "https://m2-helper.com/resources/guides/dungeons/250px-Hydra.png",
"searchText": "ship defense / hydra very lucrative dungeon from level 90 with animals race hydra ship defense cape dragonfire pass hydra chest nessie egg ebony box enchant item upgrade item book of awakening animals water"
},
{
"id": "dungeon-jotun",
"page": "dungeons.html#jotun",
"title": "Erebos / Jotun Thrym",
"description": "Has the highest group size requirement from Level 95 with animals and esoteric races",
"keywords": [
"erebos",
"jotun",
"thrym",
"enchanted forest",
"stone of dryads",
"bagjanamu chest",
"jotun thrym chest",
"yang",
"animals",
"esoteric",
"earth",
"wind"
],
"category": "guides",
"icon": "https://m2-helper.com/resources/guides/dungeons/250px-Jotun_Thrym.png",
"searchText": "erebos / jotun thrym has the highest group size requirement from level 95 with animals and esoteric races erebos jotun thrym enchanted forest stone of dryads bagjanamu chest jotun thrym chest yang animals esoteric earth wind"
},
{
"id": "bazar",
"page": "bazar.html",
"title": "Online Bazar",
"description": "Find equipment from all servers",
"keywords": [
"bazar",
"market",
"equipment",
"item",
"search",
"trade"
],
"category": "tools",
"icon": "https://m2-helper.com/resources/bazar/Glas_des_Handels.png",
"searchText": "online bazar find equipment from all servers bazar market equipment item search trade"
},
{
"id": "mercenaries",
"page": "mercenaries.html",
"title": "Mercenary System",
"description": "Guide to the mercenary system – leveling mercenaries, specializations, abilities and rewards",
"keywords": [
"mercenary", "mercenaries", "recruit", "license", "mercenary license",
"teacher", "trainer", "leveling", "training", "stamina", "champion level",
"mission", "assignment",
"normal", "skillful", "strong", "experienced", "collector", "lucky",
"scout", "fighter", "rescuer", "gatherer", "lucky charm",
"specialization", "ability",
"risky advantage", "increase success chance", "reduced injury chance",
"reduce mission duration", "extra champion level exp",
"success chance", "injury risk", "mission duration", "reward"
],
"category": "guides",
"icon": "https://m2-helper.com/resources/guides/söldner.png",
"searchText": "mercenary system guide recruit license teacher trainer leveling stamina champion level normal skillful strong experienced collector lucky scout fighter rescuer gatherer lucky charm specialization ability risky advantage increase success chance reduced injury chance extra champion level exp reward"
}
],
"tr": [
{
"id": "home",
"page": "index.html",
"title": "Ana Sayfa",
"description": "Metin2 için wiki, araçlar ve topluluğa dair merkezi adresiniz",
"keywords": [
"ana",
"başlangıç"
],
"category": "main",
"icon": "https://m2-helper.com/resources/söldner_2.png",
"searchText": "ana sayfa metin2 için wiki, araçlar ve topluluğa dair merkezi adresiniz ana başlangıç"
},
{
"id": "guides",
"page": "guides.html",
"title": "Rehberler",
"description": "Tüm alanlar için kapsamlı eğitimler ve stratejiler",
"keywords": [
"rehber",
"kılavuz",
"yardım"
],
"category": "guides",
"icon": "https://m2-helper.com/resources/guides/quest.png",
"searchText": "rehberler tüm alanlar için kapsamlı eğitimler ve stratejiler rehber kılavuz yardım"
},
{
"id": "server-guide",
"page": "server.html",
"title": "Sunucu Rehberi",
"description": "Sizin için doğru sunucuyu bulun",
"keywords": [
"sunucu",
"başlangıç",
"seçim"
],
"category": "guides",
"icon": "https://m2-helper.com/resources/guides/server.png",
"searchText": "sunucu rehberi sizin için doğru sunucuyu bulun sunucu başlangıç seçim"
},
{
"id": "dragon-alchemy",
"page": "dragon-alchemy.html",
"title": "Ejderha Taşı Simyası",
"description": "Ejderha taşı simyası ve taş iyileştirme için eksiksiz rehber",
"keywords": [
"ejderha",
"taş",
"simya",
"Ejder Alevleri",
"Zaman İksirlerine",
"Zaman Penseleri",
"Ejder Pensesi+",
"yakut",
"elmas",
"ametist",
"oniks",
"garnit",
"safir",
"yeşim"
],
"category": "systems",
"icon": "https://m2-helper.com/resources/guides/alchemy.png",
"searchText": "ejderha taşı simyası ejderha taşı simyası ve taş iyileştirme için eksiksiz rehber ejderha taş simya Ejder Alevleri Zaman İksirlerine Zaman Penseleri Ejder Pensesi+ yakut elmas ametist oniks garnit safir yeşim"
},
{
"id": "echoes-of-power",
"page": "echoes-of-power.html",
"title": "Güç Yankıları",
"description": "Güç Yankıları sistemi ve ödüller için rehber",
"keywords": [
"güç",
"yankı",
"ödül",
"güç yankısı",
"yetenek yankısı"
],
"category": "systems",
"icon": "https://m2-helper.com/resources/guides/Echos_der_Macht.png",
"searchText": "güç yankıları güç yankıları sistemi ve ödüller için rehber güç yankı ödül güç yankısı yetenek yankısı"
},
{
"id": "metin-plus",
"page": "metin-plus.html",
"title": "Metin+",
"description": "Metin+ sistemi ve özel özellikleri için rehber",
"keywords": [
"metin+",
"premium",
"özellik"
],
"category": "systems",
"icon": "https://m2-helper.com/resources/guides/m2+.png",
"searchText": "metin+ metin+ sistemi ve özel özellikleri için rehber metin+ premium özellik"
},
{
"id": "donation-guild",
"page": "donation-guild.html",
"title": "Bağış Loncası",
"description": "Bağış loncası takibi için açık araç",
"keywords": [
"bağış",
"lonca",
"takip",
"Cesaret Madalyaları"
],
"category": "miscellaneous",
"icon": "https://m2-helper.com/resources/guides/server2.png",
"searchText": "bağış loncası bağış loncası takibi için açık araç bağış lonca takip Cesaret Madalyaları"
},
{
"id": "miscellaneous",
"page": "miscellaneous.html",
"title": "Çeşitli",
"description": "Metin2 için daha fazla yararlı rehber ve ipuçları",
"keywords": [
"çeşitli",
"ipuçları",
"aura",
"cüppe",
"gaya",
"mücevher",
"rütbe",
"puan",
"sss",
"sık",
"sorular",
"yükseltme",
"şans",
"ejderha",
"taş",
"bonus",
"düşür",
"ruh",
"taşı"
],
"category": "miscellaneous",
"icon": "https://m2-helper.com/resources/guides/scroll_open.png",
"searchText": "çeşitli metin2 için daha fazla yararlı rehber ve ipuçları çeşitli ipuçları aura cüppe gaya mücevher rütbe puan sss sık sorular yükseltme şans ejderha taş bonus düşür ruh taşı"
},
{
"id": "loot-filter",
"page": "loot-filter.html",
"title": "Ganimet Filtresi Ayarları",
"description": "Aranan bir eşya için doğru kategoriyi bulun",
"keywords": [
"ganimet filtre",
"loot filter",
"ganimet",
"filtre",
"eşya",
"ayarlar",
"düşür"
],
"category": "tools",
"icon": "https://m2-helper.com/resources/guides/other/Loot-Pass.png",
"searchText": "ganimet filtresi ayarları aranan bir eşya için doğru kategoriyi bulun ganimet filtre loot filter ganimet filtre eşya ayarlar düşür"
},
{
"id": "timer",
"page": "timer.html",
"title": "Timer",
"description": "Bireysel zamanlayıcılar oluşturun ve takım arkadaşlarınızla kullanın",
"keywords": [
"zamanlayıcı",
"timer",
"boss",
"raid",
"grup",
"kanal",
"channel",
"doğuş",
"spawn",
"respawn",
"koordinasyon",
"takım",
"gerçek zamanlı",
"senkronizasyon",
"bireysel",
"arkadaş"
],
"category": "tools",
"icon": "https://m2-helper.com/resources/accelerator.png",
"searchText": "timer bireysel zamanlayıcılar oluşturun ve takım arkadaşlarınızla kullanın zamanlayıcı timer boss raid grup kanal channel doğuş spawn respawn koordinasyon takım gerçek zamanlı senkronizasyon bireysel arkadaş"
},
{
"id": "aura-calculator",
"page": "miscellaneous.html#aura-calculator",
"title": "Aura Cüppe Hesaplayıcı",
"description": "Aura cüppe seviyelendirme için maliyetleri ve kaynakları hesaplayın",
"keywords": [
"aura",
"cüppe",
"kıyafet",
"hesaplayıcı",
"ateş rün",
"seviye",
"maliyet",
"kaynaklar",
"parlayan aura cüppe",
"sıradan aura cüppe",
"buz rün",
"güç aurası"
],
"category": "tools",
"icon": "https://m2-helper.com/resources/guides/other/Strahlendes_Auragewand.png",
"searchText": "aura cüppe hesaplayıcı aura cüppe seviyelendirme için maliyetleri ve kaynakları hesaplayın aura cüppe kıyafet hesaplayıcı ateş rün seviye maliyet kaynaklar parlayan aura cüppe sıradan aura cüppe buz rün güç aurası"
},
{
"id": "gaya-calculator",
"page": "miscellaneous.html#gaya-calculator",
"title": "Gaya Hesaplayıcı",
"description": "Mücevher taşları ve zihin taşı demetlerinden ne kadar Gaya elde edeceğinizi hesaplayın",
"keywords": [
"gaya",
"hesaplayıcı",
"mücevher",
"süs taşı",
"zihin taşı demeti",
"meleys ini",
"meley",
"malzemeler",
"kaynaklar"
],
"category": "tools",
"icon": "https://m2-helper.com/resources/guides/other/Gaya.png",
"searchText": "gaya hesaplayıcı mücevher taşları ve zihin taşı demetlerinden ne kadar gaya elde edeceğinizi hesaplayın gaya hesaplayıcı mücevher süs taşı zihin taşı demeti meleys ini meley malzemeler kaynaklar"
},
{
"id": "rank-points",
"page": "miscellaneous.html#rank-points",
"title": "Rütbe Puanları Rehberi",
"description": "Rütbe puanları sistemi ve nasıl kazanılacağı hakkında her şey",
"keywords": [
"rütbe",
"puan",
"negatif",
"zen fasulyesi",
"bilge kral sembolü",
"hasar bonusu",
"bilge kral",
"rütbe kaybı",
"ölüm",
"hesaplayıcı"
],
"category": "guides",
"icon": "https://m2-helper.com/resources/guides/other/Zen-Bohne.png",
"searchText": "rütbe puanları rehberi rütbe puanları sistemi ve nasıl kazanılacağı hakkında her şey rütbe puan negatif zen fasulyesi bilge kral sembolü hasar bonusu bilge kral rütbe kaybı ölüm hesaplayıcı"
},
{
"id": "events",
"page": "events.html",
"title": "Etkinlik Yardımcı",
"description": "Tüm etkinlikler için genel bakış ve yardım araçları",
"keywords": [
"etkinlik",
"yardım",
"okey",
"tombola",
"hazine",
"avcılık",
"yeraltı",
"yutnori",
"kart",
"oyun",
"Kralı Yakala",
"Kahin Yarışması"
],
"category": "tools",
"icon": "https://m2-helper.com/resources/guides/events.png",
"searchText": "etkinlik yardımcı tüm etkinlikler için genel bakış ve yardım araçları etkinlik yardım okey tombola hazine avcılık yeraltı yutnori kart oyun Kralı Yakala Kahin Yarışması"
},
{
"id": "bio-calculator",
"page": "bio.html",
"title": "Biyolog Hızlandırıcı Hesaplayıcı",
"description": "Biyolog görevlerinde ilerlemenizi en iyi şekilde hesaplayın",
"keywords": [
"biyolog",
"hızlandırıcı",
"hesaplayıcı"
],
"category": "tools",
"icon": "https://m2-helper.com/resources/accelerator.png",
"searchText": "biyolog hızlandırıcı hesaplayıcı biyolog görevlerinde ilerlemenizi en iyi şekilde hesaplayın biyolog hızlandırıcı hesaplayıcı"
},
{
"id": "horse-calculator",
"page": "horse.html",
"title": "At Seviyesi Hesaplayıcı",
"description": "At seviye atlama için maliyetleri ve at yemini hesaplayın",
"keywords": [
"at",
"seviye",
"hesaplayıcı",
"yem"
],
"category": "tools",
"icon": "https://m2-helper.com/resources/Goldenes_Pferdebuch.png",
"searchText": "at seviyesi hesaplayıcı at seviye atlama için maliyetleri ve at yemini hesaplayın at seviye hesaplayıcı yem"
},
{
"id": "pet-calculator",
"page": "pet.html",
"title": "Pet Seviyesi Hesaplayıcı",
"description": "Pet sistemi için ipuçları, püf noktaları ve hesaplayıcı",
"keywords": [
"pet",
"seviye",
"hesaplayıcı"
],
"category": "tools",
"icon": "https://m2-helper.com/resources/Transportbox.png",
"searchText": "pet seviyesi hesaplayıcı pet sistemi için ipuçları, püf noktaları ve hesaplayıcı pet seviye hesaplayıcı"
},
{
"id": "guild-logo",
"page": "guild-logo.html",
"title": "Lonca Logo Düzenleyici",
"description": "Resminizi Metin2 uyumlu lonca logosuna dönüştürün",
"keywords": [
"lonca logo",
"lonca",
"logo",
"tga",
"piksel",
"editör",
"dönüştürücü",
"resim"
],
"category": "tools",
"icon": "https://m2-helper.com/resources/guides/gilden-logo.png",
"searchText": "lonca logo düzenleyici resminizi metin2 uyumlu lonca logosuna dönüştürün lonca logo tga piksel editör dönüştürücü resim 16x12 indir pixelart"
},
{
"id": "leveling",
"page": "leveling.html",
"title": "Seviye Rehberi",
"description": "Tüm seviyeler için optimal seviye yolları ve deneyim ipuçları",
"keywords": [
"seviye",
"leveling",
"exp",
"deneyim",
"rehber",
"yol",
"düşük seviye",
"orta seviye",
"yüksek seviye",
"şampiyon",
"sl1",
"sl10",
"harita",
"mağara",
"öz 2",
"öz 3",
"şeytan kulesi",
"ochao tapınağı",
"büyülü orman",
"zaman yırtığı",
"zy",
"gizemli zindan",
"hırs uçurumu",
"yohara",
"exp bonusu",
"grup bonusu",
"tecrübe yüzüğü",
"bilgelik iksiri",
"göreceli exp",
"paralı asker görevler",
"sung mahi"
],
"category": "guides",
"icon": "https://m2-helper.com/resources/exp.png",
"searchText": "seviye rehberi tüm seviyeler için optimal seviye yolları ve deneyim ipuçları seviye leveling exp deneyim rehber yol düşük seviye orta seviye yüksek seviye şampiyon sl1 sl10 harita mağara öz 2 öz 3 şeytan kulesi ochao tapınağı büyülü orman zaman yırtığı zy gizemli zindan hırs uçurumu yohara exp bonusu grup bonusu tecrübe yüzüğü bilgelik iksiri göreceli exp paralı asker görevler sung mahi"
},
{
"id": "dungeons",
"page": "dungeons.html",
"title": "Zindanlar",
"description": "Stratejiler ve ödüllerle tüm zindanlar için kompakt rehberler",
"keywords": [
"zindan",
"zindanlar",
"rehber",
"patron",
"örnek",
"zodiak",
"örümcek baronesi",
"lonca koşusu",
"şeytan kulesi",
"beran-setaou",
"enigmanın tapınağı",
"meley",
"hidra",
"jotun",
"nemere",
"razador",
"zaman yırtığı",
"uyanış",
"yılan koşusu",
"alastor",
"balathor"
],
"category": "guides",
"icon": "https://m2-helper.com/resources/guides/Schatzrolle.png",
"searchText": "zindanlar stratejiler ve ödüllerle tüm zindanlar için kompakt rehberler zindan zindanlar rehber patron örnek zodiak örümcek baronesi lonca koşusu şeytan kulesi beran-setaou enigmanın tapınağı meley hidra jotun nemere razador zaman yırtığı uyanış yılan koşusu alastor balathor"
},
{
"id": "dungeon-zodiac",
"page": "dungeons.html#zodiac",
"title": "Zodyak Tapınağı",
"description": "Haftanın gününe bağlı olarak 40 katlı zindan Seviye 20'den itibaren",
"keywords": [
"zodyak",
"tapınak",
"anima küresi",
"altın zodyak sandığı",
"kırmızı zodyak sandığı",
"kat"
],
"category": "guides",
"icon": "https://m2-helper.com/resources/guides/dungeons/250px-Wächter_Chen.png",
"searchText": "zodyak tapınağı haftanın gününe bağlı olarak 40 katlı zindan seviye 20'den itibaren zodyak tapınak anima küresi altın zodyak sandığı kırmızı zodyak sandığı kat"
},
{
"id": "dungeon-guildrun",
"page": "dungeons.html#guildrun",
"title": "Ejderha Kralı Sarayı",
"description": "Loncalar için haftalık zindanlar Seviye 70'den itibaren",
"keywords": [
"saray",
"ejderha kralı",
"lonca koşusu",
"kral anahtarı",
"cesaret madalyası",
"lonca",
"haftalık"
],
"category": "guides",
"icon": "https://m2-helper.com/resources/guides/dungeons/gildenrun.png",
"searchText": "ejderha kralı sarayı loncalar için haftalık zindanlar seviye 70'den itibaren saray ejderha kralı lonca koşusu kral anahtarı cesaret madalyası lonca haftalık"
},
{
"id": "dungeon-spider-baroness",
"page": "dungeons.html#spider-baroness",
"title": "Örümcek Baronesi Yuvası",
"description": "Böcekler ırkı ile Seviye 50'den itibaren ilk zindanlardan biri",
"keywords": [
"örümcek",
"baronesi",
"yuva",
"örümcek anahtarı",
"pet kitap sandığı",
"ışınlanma yüzüğü",
"geçiş",
"titan kalkanı",
"böcekler"
],
"category": "guides",
"icon": "https://m2-helper.com/resources/guides/dungeons/250px-Spinnenbaroness.png",
"searchText": "örümcek baronesi yuvası böcekler ırkı ile seviye 50'den itibaren ilk zindanlardan biri örümcek baronesi yuva örümcek anahtarı pet kitap sandığı ışınlanma yüzüğü geçiş titan kalkanı böcekler"
},
{
"id": "dungeon-demon-tower",
"page": "dungeons.html#demon-tower",
"title": "İblis Kulesi",
"description": "Ölümsüzler ırkı ile Seviye 40'tan itibaren 9 katlı klasik zindan",
"keywords": [
"iblis",
"kule",
"küçültülmüş kafa",
"arama camı",
"ölümsüzler",
"şeytanlar",
"hwang tapınağı"
],
"category": "guides",
"icon": "https://m2-helper.com/resources/guides/dungeons/202px-Sensenmann.png",
"searchText": "i̇blis kulesi ölümsüzler ırkı ile seviye 40'tan itibaren 9 katlı klasik zindan iblis kule küçültülmüş kafa arama camı ölümsüzler şeytanlar hwang tapınağı"
},
{
"id": "dungeon-devils-catacomb",
"page": "dungeons.html#devils-catacomb",
"title": "Şeytan Mezarlığı",
"description": "İblis Kulesi'nin devamı Seviye 75'ten itibaren Ölümsüzler ırkı ile",
"keywords": [
"şeytan",
"mezarlık",
"küçültülmüş kafa",
"titan kalkanı",
"ölümsüzler",
"hwang tapınağı"
],
"category": "guides",
"icon": "https://m2-helper.com/resources/guides/dungeons/250px-Azrael.png",
"searchText": "şeytan mezarlığı i̇blis kulesi'nin devamı seviye 75'ten itibaren ölümsüzler ırkı ile şeytan mezarlık küçültülmüş kafa titan kalkanı ölümsüzler hwang tapınağı"
},
{
"id": "dungeon-beran-setaou",
"page": "dungeons.html#beran-setaou",
"title": "Ejderha Beran-Setaou",
"description": "Hayvanlar ve Orklar ırkları ile Seviye 75'ten itibaren ilk değerli düşük seviye zindanı",
"keywords": [
"beran",
"setaou",
"ejderha",
"kıvrık anahtar",
"ejderha odası girişi",
"beran sandığı",
"eşya geliştir",
"eşya büyüle",
"yang",
"hayvanlar",
"orklar",
"sürgün mağarası"
],
"category": "guides",
"icon": "https://m2-helper.com/resources/guides/dungeons/Beran-Setaou.png",
"searchText": "ejderha beran-setaou hayvanlar ve orklar ırkları ile seviye 75'ten itibaren ilk değerli düşük seviye zindanı beran setaou ejderha kıvrık anahtar ejderha odası girişi beran sandığı eşya geliştir eşya büyüle yang hayvanlar orklar sürgün mağarası"
},
{
"id": "dungeon-enigma-c",
"page": "dungeons.html#enigmaC",
"title": "Enigma Tapınağı C",
"description": "Irksız ile Seviye 75-90 değişen konumlu rastgele zindan",
"keywords": [
"enigma",
"tapınak",
"derece c",
"hazine tomarı",
"hazine sandığı",
"bonus",
"irksız",
"rastgele"
],
"category": "guides",
"icon": "https://m2-helper.com/resources/guides/dungeons/Schatzrolle_(Grad_C).png",
"searchText": "enigma tapınağı c irksız ile seviye 75-90 değişen konumlu rastgele zindan enigma tapınak derece c hazine tomarı hazine sandığı bonus irksız rastgele"
},
{
"id": "dungeon-enigma-b",
"page": "dungeons.html#enigmaB",
"title": "Enigma Tapınağı B",
"description": "Irksız ile Seviye 90-120 değişen konumlu rastgele zindan",
"keywords": [
"enigma",
"tapınak",
"derece b",
"hazine tomarı",
"hazine sandığı",
"bonus",
"irksız",
"rastgele"
],
"category": "guides",
"icon": "https://m2-helper.com/resources/guides/dungeons/Schatzrolle_(Grad_B).png",
"searchText": "enigma tapınağı b irksız ile seviye 90-120 değişen konumlu rastgele zindan enigma tapınak derece b hazine tomarı hazine sandığı bonus irksız rastgele"
},
{
"id": "dungeon-enigma-a",
"page": "dungeons.html#enigmaA",
"title": "Enigma Tapınağı A",
"description": "Irksız ile Şampiyon Seviye 1'den itibaren değişen konumlu rastgele zindan",
"keywords": [
"enigma",
"tapınak",
"derece a",
"hazine tomarı",
"hazine sandığı",
"bonus",
"irksız",
"rastgele",
"şampiyon",
"at yetenekleri"
],
"category": "guides",
"icon": "https://m2-helper.com/resources/guides/dungeons/Schatzrolle_(Grad_A).png",
"searchText": "enigma tapınağı a irksız ile şampiyon seviye 1'den itibaren değişen konumlu rastgele zindan enigma tapınak derece a hazine tomarı hazine sandığı bonus irksız rastgele şampiyon at yetenekleri"
},
{
"id": "dungeon-serpent-temple",
"page": "dungeons.html#serpent-temple",
"title": "Yılan Tapınağı",
"description": "Hayvanlar, Ezoterik ve Yarı-İnsanlar ırkları ile Şampiyon Seviye 1'den itibaren yılan zırhı için malzeme sağlar",
"keywords": [
"yılan",
"tapınak",
"yilad geçidi",
"yılan hazinesi",
"yılan pelerini",
"hayvanlar",
"ezoterik",
"yarı-insanlar",
"yohara",
"ateş",
"su",
"toprak",
"rüzgar",
"şimşek"
],
"category": "guides",
"icon": "https://m2-helper.com/resources/guides/dungeons/250px-Schlangenkönigin_Nethis_(Erde).png",
"searchText": "yılan tapınağı hayvanlar, ezoterik ve yarı-i̇nsanlar ırkları ile şampiyon seviye 1'den itibaren yılan zırhı için malzeme sağlar yılan tapınak yilad geçidi yılan hazinesi yılan pelerini hayvanlar ezoterik yarı-insanlar yohara ateş su toprak rüzgar şimşek"
},
{
"id": "dungeon-alastor",
"page": "dungeons.html#alastor",
"title": "Alastor (kolay / zor)",
"description": "Hayvanlar, Ezoterik ve Yarı-İnsanlar ırkları ile Şampiyon Seviye 1'den itibaren yılan silahı için malzeme sağlar",
"keywords": [
"alastor",
"kuzey rüzgar derinlikleri",
"donmuş anahtar",
"beyaz ejderha sandığı",
"hayvanlar",
"ezoterik",
"yarı-insanlar",
"yohara",
"su",
"buz"
],
"category": "guides",
"icon": "https://m2-helper.com/resources/guides/dungeons/alastor.png",
"searchText": "alastor (kolay / zor) hayvanlar, ezoterik ve yarı-i̇nsanlar ırkları ile şampiyon seviye 1'den itibaren yılan silahı için malzeme sağlar alastor kuzey rüzgar derinlikleri donmuş anahtar beyaz ejderha sandığı hayvanlar ezoterik yarı-insanlar yohara su buz"
},
{
"id": "dungeon-balathor",
"page": "dungeons.html#balathor",
"title": "Balathor'un Mezarı",
"description": "Ezoterik ve Yarı-İnsanlar ırkları ile Şampiyon Seviye 4'ten itibaren ileri düzey oyuncular için lonca zindanı",
"keywords": [
"balathor",
"mezar",
"sohan dağı",
"balathor buz sandığı",
"ezoterik",
"yarı-insanlar",
"lonca",
"yohara",
"buz"
],
"category": "guides",
"icon": "https://m2-helper.com/resources/guides/dungeons/balathor.png",
"searchText": "balathor'un mezarı ezoterik ve yarı-i̇nsanlar ırkları ile şampiyon seviye 4'ten itibaren ileri düzey oyuncular için lonca zindanı balathor mezar sohan dağı balathor buz sandığı ezoterik yarı-insanlar lonca yohara buz"
},
{
"id": "dungeon-meley-group",
"page": "dungeons.html#meley-group",
"title": "Meleys İni - Grup",
"description": "Irksız ile Seviye 75'ten itibaren sadece Gaya için grup zindanı",
"keywords": [
"meley",
"meleys",
"in",
"grup",
"gaya",
"mücevher taşı",
"ateş diyarı",
"irksız",
"ateş"
],
"category": "guides",
"icon": "https://m2-helper.com/resources/guides/dungeons/meley.png",
"searchText": "meleys i̇ni - grup irksız ile seviye 75'ten itibaren sadece gaya için grup zindanı meley meleys in grup gaya mücevher taşı ateş diyarı irksız ateş"
},
{
"id": "dungeon-meley-guild",
"page": "dungeons.html#meley-guild",
"title": "Meleys İni - Lonca",
"description": "Irksız ile Seviye 90 oyuncular için lonca zindanı",
"keywords": [
"meley",
"meleys",
"in",
"lonca",
"kraliçe meley sandığı",
"ejderha koruyucusu sandığı",
"ateş diyarı",
"irksız",
"ateş",
"ninja"
],
"category": "guides",
"icon": "https://m2-helper.com/resources/guides/dungeons/meley.png",
"searchText": "meleys i̇ni - lonca irksız ile seviye 90 oyuncular için lonca zindanı meley meleys in lonca kraliçe meley sandığı ejderha koruyucusu sandığı ateş diyarı irksız ateş ninja"
},
{
"id": "dungeon-razador",
"page": "dungeons.html#razador",
"title": "Kızıl Ejderha Kalesi / Razador",
"description": "Şeytanlar ırkı ile Seviye 100'den itibaren deneyimli oyuncular için son oyun zindanı",
"keywords": [
"razador",
"kızıl ejderha kalesi",
"razador sandığı",
"ateş diyarı",
"şeytanlar",
"ateş",
"karanlık",
"karanlık sütun",
"morun"
],
"category": "guides",
"icon": "https://m2-helper.com/resources/guides/dungeons/250px-Razador.png",
"searchText": "kızıl ejderha kalesi / razador şeytanlar ırkı ile seviye 100'den itibaren deneyimli oyuncular için son oyun zindanı razador kızıl ejderha kalesi razador sandığı ateş diyarı şeytanlar ateş karanlık karanlık sütun morun"
},
{
"id": "dungeon-nemere",
"page": "dungeons.html#nemere",
"title": "Nemere'nin Kulesi",
"description": "Ezoterik ırkı ile Seviye 100'den itibaren ilk değerli zindanlar arasında sayılır",
"keywords": [
"nemere",
"nemere kulesi",
"nemere sandığı",
"sohan dağı",
"ezoterik",
"buz",
"ninja",
"ejderha şamanı"
],
"category": "guides",
"icon": "https://m2-helper.com/resources/guides/dungeons/250px-Nemere.png",
"searchText": "nemere'nin kulesi ezoterik ırkı ile seviye 100'den itibaren ilk değerli zindanlar arasında sayılır nemere nemere kulesi nemere sandığı sohan dağı ezoterik buz ninja ejderha şamanı"
},
{
"id": "dungeon-time-rift",
"page": "dungeons.html#time-rift",
"title": "Zaman Yarığı Zindanları",
"description": "Hayvanlar, Orklar, Şeytanlar ve Ezoterik ırkları ile Seviye 110'dan itibaren sadece leveling için kullanılır",
"keywords": [
"zaman yarığı",
"cep saati",
"uyanış kitabı",
"illüzyonlar platosu",
"hayvanlar",
"orklar",
"şeytanlar",
"ezoterik",
"ateş",
"su",
"toprak",
"şimşek",
"karanlık",
"buz"
],
"category": "guides",
"icon": "https://m2-helper.com/resources/guides/dungeons/erweckung-zeitriss.png",
"searchText": "zaman yarığı zindanları hayvanlar, orklar, şeytanlar ve ezoterik ırkları ile seviye 110'dan itibaren sadece leveling için kullanılır zaman yarığı cep saati uyanış kitabı illüzyonlar platosu hayvanlar orklar şeytanlar ezoterik ateş su toprak şimşek karanlık buz"
},
{
"id": "dungeon-redux",
"page": "dungeons.html#redux",
"title": "Uyanış Zindanları",
"description": "Hayvanlar, Orklar, Şeytanlar ve Ezoterik ırkları ile Seviye 110'dan itibaren zorlu uyanış zindanları",
"keywords": [
"uyanış",
"uyanış kitabı",
"uyanış sandığı",
"uy beran",
"uy jotun",
"uy razador",
"uy nemere",
"illüzyonlar platosu",
"hayvanlar",
"orklar",
"şeytanlar",
"ezoterik",
"ateş",
"su",
"toprak",
"şimşek",
"karanlık",
"buz"
],
"category": "guides",
"icon": "https://m2-helper.com/resources/guides/dungeons/erweckung-zeitriss.png",
"searchText": "uyanış zindanları hayvanlar, orklar, şeytanlar ve ezoterik ırkları ile seviye 110'dan itibaren zorlu uyanış zindanları uyanış uyanış kitabı uyanış sandığı uy beran uy jotun uy razador uy nemere illüzyonlar platosu hayvanlar orklar şeytanlar ezoterik ateş su toprak şimşek karanlık buz"
},
{
"id": "dungeon-hydra",
"page": "dungeons.html#hydra",
"title": "Gemi Savunması / Hydra",
"description": "Hayvanlar ırkı ile Seviye 90'dan itibaren çok kazançlı zindan",
"keywords": [
"hydra",
"gemi savunması",
"ejderha ateşi burnu",
"geçiş belgesi",
"hydra sandığı",
"nessie yumurtası",
"abanoz kutu",
"eşya büyüle",
"eşya geliştir",
"uyanış kitabı",
"hayvanlar",
"su"
],
"category": "guides",
"icon": "https://m2-helper.com/resources/guides/dungeons/250px-Hydra.png",
"searchText": "gemi savunması / hydra hayvanlar ırkı ile seviye 90'dan itibaren çok kazançlı zindan hydra gemi savunması ejderha ateşi burnu geçiş belgesi hydra sandığı nessie yumurtası abanoz kutu eşya büyüle eşya geliştir uyanış kitabı hayvanlar su"
},
{
"id": "dungeon-jotun",
"page": "dungeons.html#jotun",
"title": "Erebos / Jotun Thrym",
"description": "Hayvanlar ve Ezoterik ırkları ile Seviye 95'ten itibaren grup büyüklüğü için en yüksek gereksinimlere sahip",
"keywords": [
"erebos",
"jotun",
"thrym",
"büyülü orman",
"dryad taşı",
"bagjanamu sandığı",
"jotun thrym sandığı",
"yang",
"hayvanlar",
"ezoterik",
"toprak",
"rüzgar"
],
"category": "guides",
"icon": "https://m2-helper.com/resources/guides/dungeons/250px-Jotun_Thrym.png",
"searchText": "erebos / jotun thrym hayvanlar ve ezoterik ırkları ile seviye 95'ten itibaren grup büyüklüğü için en yüksek gereksinimlere sahip erebos jotun thrym büyülü orman dryad taşı bagjanamu sandığı jotun thrym sandığı yang hayvanlar ezoterik toprak rüzgar"
},
{
"id": "bazar",
"page": "bazar.html",
"title": "Online Bazar",
"description": "Tüm sunuculardan ekipman bulun",
"keywords": [
"bazar",
"pazar",
"ekipman",
"eşya",
"arama"
],
"category": "tools",
"icon": "https://m2-helper.com/resources/bazar/Glas_des_Handels.png",
"searchText": "online bazar tüm sunuculardan ekipman bulun bazar pazar ekipman eşya arama"
},
{
"id": "mercenaries",
"page": "mercenaries.html",
"title": "Paralı Asker Sistemi",
"description": "Paralı asker sistemi rehberi – seviyeleme, uzmanlaşmalar, yetenekler ve ödüller",
"keywords": [
"paralı asker", "söldner", "işe al", "lisans", "paralı asker lisansı",
"öğretmen", "eğitmen", "seviyeleme", "eğitim", "dayanıklılık", "şampiyon seviye",
"görev", "atama",
"normal", "yetenekli", "güçlü", "deneyimli", "toplayıcı", "şanslı",
"izci", "savaşçı", "kurtarıcı", "şans getiren",
"uzmanlaşma", "yetenek",
"riskli avantaj", "başarı şansını artır", "yaralanma şansını azalt",
"görev süresini kısalt", "ekstra şampiyon exp",
"başarı şansı", "yaralanma riski", "ödül"
],
"category": "guides",
"icon": "https://m2-helper.com/resources/guides/söldner.png",
"searchText": "paralı asker sistemi rehberi işe al lisans öğretmen eğitmen seviyeleme dayanıklılık şampiyon seviye görev normal yetenekli güçlü deneyimli toplayıcı şanslı izci savaşçı kurtarıcı şans getiren uzmanlaşma yetenek riskli avantaj başarı şansı yaralanma riski ödül"
}
]
};
if (typeof module !== 'undefined' && module.exports) {
module.exports = SEARCH_INDEX;
}